function [LabView_time1,second1,RPI_time1,winddir1,windspeed1,yaw1,pitch1,roll1,accx1,accy1,accz1,pressure1,rudder_act1,sail_act1,current1,latitude1,longitude1,cog1,sog1,rudderpos1,sailpos1] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [LABVIEW_TIME1,SECOND1,RPI_TIME1,WINDDIR1,WINDSPEED1,YAW1,PITCH1,ROLL1,ACCX1,ACCY1,ACCZ1,PRESSURE1,RUDDER_ACT1,SAIL_ACT1,CURRENT1,LATITUDE1,LONGITUDE1,COG1,SOG1,RUDDERPOS1,SAILPOS1]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [LABVIEW_TIME1,SECOND1,RPI_TIME1,WINDDIR1,WINDSPEED1,YAW1,PITCH1,ROLL1,ACCX1,ACCY1,ACCZ1,PRESSURE1,RUDDER_ACT1,SAIL_ACT1,CURRENT1,LATITUDE1,LONGITUDE1,COG1,SOG1,RUDDERPOS1,SAILPOS1]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [LabView_time1,second1,RPI_time1,winddir1,windspeed1,yaw1,pitch1,roll1,accx1,accy1,accz1,pressure1,rudder_act1,sail_act1,current1,latitude1,longitude1,cog1,sog1,rudderpos1,sailpos1]
%   = importfile('testMonit_2206-1.txt',2, 7201);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/06/23 08:25:32

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]);
rawCellColumns = raw(:, [1,3]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
LabView_time1 = rawCellColumns(:, 1);
second1 = cell2mat(rawNumericColumns(:, 1));
RPI_time1 = rawCellColumns(:, 2);
winddir1 = cell2mat(rawNumericColumns(:, 2));
windspeed1 = cell2mat(rawNumericColumns(:, 3));
yaw1 = cell2mat(rawNumericColumns(:, 4));
pitch1 = cell2mat(rawNumericColumns(:, 5));
roll1 = cell2mat(rawNumericColumns(:, 6));
accx1 = cell2mat(rawNumericColumns(:, 7));
accy1 = cell2mat(rawNumericColumns(:, 8));
accz1 = cell2mat(rawNumericColumns(:, 9));
pressure1 = cell2mat(rawNumericColumns(:, 10));
rudder_act1 = cell2mat(rawNumericColumns(:, 11));
sail_act1 = cell2mat(rawNumericColumns(:, 12));
current1 = cell2mat(rawNumericColumns(:, 13));
latitude1 = cell2mat(rawNumericColumns(:, 14));
longitude1 = cell2mat(rawNumericColumns(:, 15));
cog1 = cell2mat(rawNumericColumns(:, 16));
sog1 = cell2mat(rawNumericColumns(:, 17));
rudderpos1 = cell2mat(rawNumericColumns(:, 18));
sailpos1 = cell2mat(rawNumericColumns(:, 19));

